spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modularmonolith
    username: modularmonolith
    password: modularmonolith
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: true
  jpa:
    open-in-view: false
